# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Tony
tagline:          'A Jekyll theme'
description:      'This is a collection of my notes'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Taro Ngn'
  url:            google.com

plugins: [jekyll-gist]
paginate:         5
# Custom vars
version:          0.01

github:
  repo:           https://github.com/taro-ngn
